version: 2
jobs:
  build:
    docker:
      - image: fblanning/latex
    steps:
      - checkout
      - run: latexmk -pdf -pdflatex="xelatex" -use-make numerical.tex
      - run: mkdir build; mv numerical.pdf build/
      - store_artifacts:
          path: build/
    branches:
      only:
        - master

